import { AlertTriangle, BarChart3, Download, FileText, Key, Lightbulb, Target, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import toast from 'react-hot-toast';
import FileUpload from '../components/FileUpload';
import { useApiKey } from '../context/ApiKeyContext';
import { DocumentProcessor } from '../services/documentProcessor';
import { ResumeAnalyzer as ResumeAnalyzerService } from '../services/resumeAnalyzer';
import { TextFormatter } from '../utils/textFormatter';

const ResumeAnalyzer = () => {
  const { geminiApiKey, updateGeminiApiKey, hasGeminiKey } = useApiKey();
  const [tempApiKey, setTempApiKey] = useState('');
  const [file, setFile] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [analysisResults, setAnalysisResults] = useState(null);
  const [activeTab, setActiveTab] = useState('summary');

  const handleApiKeySubmit = (e) => {
    e.preventDefault();
    if (tempApiKey.trim()) {
      updateGeminiApiKey(tempApiKey.trim());
      setTempApiKey('');
      toast.success('API key saved successfully!');
    }
  };

  const handleFileSelect = (selectedFile) => {
    setFile(selectedFile);
    if (analysisResults) {
      setAnalysisResults(null);
    }
  };

  const handleAnalyze = async () => {
    if (!file || !hasGeminiKey) {
      toast.error('Please upload a file and provide a valid API key');
      return;
    }

    setProcessing(true);
    const loadingToast = toast.loading('Analyzing your resume...');

    try {
      // Get file type for user feedback
      const fileType = DocumentProcessor.getFileType(file);
      const fileTypeText = fileType.toUpperCase();
      
      // Step 1: Process Document (PDF or DOCX)
      toast.loading(`Extracting text from ${fileTypeText}...`, { id: loadingToast });
      const documentData = await DocumentProcessor.processResumeDocument(file);
      
      // Step 2: Analyze with Gemini
      toast.loading('Performing AI analysis...', { id: loadingToast });
      const analyzer = new ResumeAnalyzerService(geminiApiKey);
      const analysis = await analyzer.performCompleteAnalysis(documentData.chunks);
      
      // Combine document data with analysis
      const results = {
        ...analysis,
        documentData,
        fileName: file.name,
        fileType: fileType
      };
      
      setAnalysisResults(results);
      toast.success('Analysis completed successfully!', { id: loadingToast });
      
    } catch (error) {
      console.error('Analysis error:', error);
      toast.error(error.message || 'Failed to analyze resume', { id: loadingToast });
    } finally {
      setProcessing(false);
    }
  };

  const downloadReport = () => {
    if (!analysisResults) return;
    
    const report = `
RESUME ANALYSIS REPORT
Generated on: ${new Date().toLocaleString()}
File: ${analysisResults.fileName}

OVERALL SCORE: ${analysisResults.rating.totalScore || analysisResults.rating.overallScore}/10
GRADE: ${analysisResults.rating.grade || 'N/A'}

PROFESSIONAL SUMMARY:
${analysisResults.professionalSummary}

DETAILED ANALYSIS:

SUMMARY:
${analysisResults.summary}

STRENGTHS:
${analysisResults.strengths}

AREAS FOR IMPROVEMENT:
${analysisResults.weaknesses}

JOB TITLE SUGGESTIONS:
${analysisResults.jobTitles}

PROFESSIONAL RATING BREAKDOWN (Based on Recruiter Standards):
- Content Quality: ${analysisResults.rating.categories?.content || analysisResults.rating.contentQuality || 'N/A'}/2
- Structure & Flow: ${analysisResults.rating.categories?.structure || analysisResults.rating.skillsPresentation || 'N/A'}/2
- Visual Formatting: ${analysisResults.rating.categories?.formatting || analysisResults.rating.experienceDescription || 'N/A'}/2
- Achievement Impact: ${analysisResults.rating.categories?.impact || analysisResults.rating.achievementHighlights || 'N/A'}/2
- ATS Compatibility: ${analysisResults.rating.categories?.ats || analysisResults.rating.educationCertifications || 'N/A'}/2

${analysisResults.rating.improvements && analysisResults.rating.improvements.length > 0 ? `
KEY IMPROVEMENT AREAS:
${analysisResults.rating.improvements.map(improvement => `- ${improvement}`).join('\n')}
` : ''}
---
Generated by AI Resume Analyzer - GenAI Hackathon 2025
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-analysis-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded successfully!');
  };

  const getScoreColor = (score) => {
    if (score >= 2) return 'text-green-600 bg-green-100';
    if (score >= 1) return 'text-yellow-600 bg-yellow-100';
    return 'text-red-600 bg-red-100';
  };

  const getScoreRing = (score) => {
    if (score >= 8) return 'text-green-500';
    if (score >= 6) return 'text-yellow-500';
    return 'text-red-500';
  };

  const getGradeColor = (grade) => {
    switch (grade) {
      case 'A': return 'text-green-800 bg-green-200';
      case 'B': return 'text-blue-800 bg-blue-200';
      case 'C': return 'text-yellow-800 bg-yellow-200';
      case 'D': return 'text-orange-800 bg-orange-200';
      case 'F': return 'text-red-800 bg-red-200';
      default: return 'text-gray-800 bg-gray-200';
    }
  };

  const tabs = [
    { id: 'summary', label: 'Summary', icon: FileText, color: 'blue', description: 'Overall resume analysis' },
    { id: 'strengths', label: 'Strengths', icon: TrendingUp, color: 'green', description: 'Key advantages & skills' },
    { id: 'weaknesses', label: 'Improvements', icon: AlertTriangle, color: 'orange', description: 'Areas to enhance' },
    { id: 'jobs', label: 'Job Suggestions', icon: Target, color: 'purple', description: 'Recommended positions' },
    { id: 'rating', label: 'Rating', icon: BarChart3, color: 'indigo', description: 'Professional scoring' }
  ];

  if (!hasGeminiKey) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-indigo-100 flex items-center justify-center p-4">
        <div className="max-w-md w-full bg-white/80 backdrop-blur-md rounded-2xl shadow-2xl p-8 border border-white/20">
          <div className="text-center mb-6">
            <div className="w-20 h-20 bg-gradient-to-br from-blue-500 via-purple-500 to-indigo-600 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105">
              <Key className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600 bg-clip-text text-transparent mb-2">API Key Required</h2>
            <p className="text-gray-600 leading-relaxed">
              Please enter your Google Gemini API key to start analyzing resumes with AI-powered insights
            </p>
          </div>
          
          <form onSubmit={handleApiKeySubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Google Gemini API Key
              </label>
              <input
                type="password"
                value={tempApiKey}
                onChange={(e) => setTempApiKey(e.target.value)}
                placeholder="Enter your Gemini API key..."
                className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 hover:border-gray-400"
                required
              />
            </div>
            <button
              type="submit"
              className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-4 rounded-xl hover:from-blue-700 hover:to-purple-700 transition-all duration-200 transform hover:scale-105 font-medium shadow-lg hover:shadow-xl"
            >
              Save API Key
            </button>
          </form>
          
          <div className="mt-6 p-4 bg-blue-50/80 rounded-xl border border-blue-200/50">
            <p className="text-xs text-blue-700 leading-relaxed">
              <strong>Note:</strong> Your API key is stored locally and used only for resume analysis. 
              Get your API key from Google AI Studio.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600 bg-clip-text text-transparent mb-2">Resume Analyzer</h1>
          <p className="text-gray-600 text-lg">
            Upload your resume and get AI-powered insights to improve your career prospects
          </p>
          
          {/* Status Indicators */}
          <div className="flex flex-wrap gap-4 mt-6">
            <div className={`flex items-center space-x-2 px-4 py-2 rounded-xl border ${
              hasGeminiKey 
                ? 'bg-green-50 border-green-200 text-green-700' 
                : 'bg-red-50 border-red-200 text-red-700'
            }`}>
              <Key className="w-4 h-4" />
              <span className="text-sm font-medium">
                API Key: {hasGeminiKey ? 'Connected' : 'Not Set'}
              </span>
              {hasGeminiKey && <span className="text-green-500">✓</span>}
              {!hasGeminiKey && <span className="text-red-500">✗</span>}
            </div>
            
            <div className={`flex items-center space-x-2 px-4 py-2 rounded-xl border ${
              file 
                ? 'bg-green-50 border-green-200 text-green-700' 
                : 'bg-gray-50 border-gray-200 text-gray-600'
            }`}>
              <FileText className="w-4 h-4" />
              <span className="text-sm font-medium">
                File: {file ? file.name : 'No file selected'}
              </span>
              {file && <span className="text-green-500">✓</span>}
            </div>
            
            <div className={`flex items-center space-x-2 px-4 py-2 rounded-xl border ${
              hasGeminiKey && file 
                ? 'bg-blue-50 border-blue-200 text-blue-700' 
                : 'bg-gray-50 border-gray-200 text-gray-600'
            }`}>
              <BarChart3 className="w-4 h-4" />
              <span className="text-sm font-medium">
                Status: {hasGeminiKey && file ? 'Ready to Analyze' : 'Setup Required'}
              </span>
              {hasGeminiKey && file && <span className="text-blue-500">✓</span>}
            </div>
          </div>
        </div>

        {/* Upload Section */}
        <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl p-8 mb-8 border border-white/20 hover:shadow-2xl transition-all duration-300">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-semibold text-gray-900 flex items-center">
              <FileText className="w-6 h-6 mr-3 text-blue-600" />
              Upload Resume
            </h2>
            
            {/* API Key Quick Setup */}
            {!hasGeminiKey && (
              <div className="flex items-center space-x-2">
                <form onSubmit={handleApiKeySubmit} className="flex items-center space-x-2">
                  <input
                    type="password"
                    placeholder="Enter Gemini API Key"
                    value={tempApiKey}
                    onChange={(e) => setTempApiKey(e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                  <button
                    type="submit"
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition-colors"
                  >
                    Save
                  </button>
                </form>
              </div>
            )}
          </div>
          
          <FileUpload 
            onFileSelect={handleFileSelect} 
            isProcessing={processing} 
          />
          
          {file && !processing && (
            <div className="mt-8 flex justify-center">
              <button
                onClick={handleAnalyze}
                disabled={processing || !hasGeminiKey}
                className="bg-gradient-to-r from-blue-600 to-purple-600 text-white px-8 py-4 rounded-xl hover:from-blue-700 hover:to-purple-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-all duration-200 flex items-center space-x-3 font-medium shadow-lg hover:shadow-xl transform hover:scale-105"
              >
                <BarChart3 className="w-5 h-5" />
                <span>Analyze Resume</span>
              </button>
            </div>
          )}
        </div>

        {/* Results Section */}
        {analysisResults && (
          <div className="space-y-8">
            {/* Quick Stats */}
            <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl p-8 border border-white/20 hover:shadow-2xl transition-all duration-300">
              <div className="flex justify-between items-center mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 flex items-center">
                  <BarChart3 className="w-6 h-6 mr-3 text-blue-600" />
                  Analysis Results
                </h2>
                <button
                  onClick={downloadReport}
                  className="flex items-center space-x-2 text-blue-600 hover:text-blue-700 transition-all duration-200 bg-blue-50 hover:bg-blue-100 px-4 py-2 rounded-xl font-medium transform hover:scale-105"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Report</span>
                </button>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div className="text-center p-6 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl border border-blue-200/50 hover:scale-105 transition-all duration-300">
                  <div className={`text-4xl font-bold mb-2 ${getScoreRing(analysisResults.rating.totalScore || analysisResults.rating.overallScore)}`}>
                    {analysisResults.rating.totalScore || analysisResults.rating.overallScore}/10
                  </div>
                  <div className="text-sm text-gray-600 font-medium">Overall Score</div>
                </div>
                <div className="text-center p-6 bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl border border-green-200/50 hover:scale-105 transition-all duration-300">
                  <div className="text-3xl font-bold text-gray-900 mb-2">
                    {analysisResults.documentData.analysis.wordCount}
                  </div>
                  <div className="text-sm text-gray-600 font-medium">Words</div>
                </div>
                <div className="text-center p-6 bg-gradient-to-br from-purple-50 to-violet-50 rounded-2xl border border-purple-200/50 hover:scale-105 transition-all duration-300">
                  <div className="text-3xl font-bold text-gray-900 mb-2">
                    {analysisResults.documentData.metadata.pageCount}
                  </div>
                  <div className="text-sm text-gray-600 font-medium">
                    {analysisResults.fileType === 'pdf' ? 'Pages' : 'Document'}
                  </div>
                </div>
                <div className="text-center p-6 bg-gradient-to-br from-orange-50 to-amber-50 rounded-2xl border border-orange-200/50 hover:scale-105 transition-all duration-300">
                  <div className="text-3xl font-bold text-gray-900 mb-2">
                    {analysisResults.documentData.analysis.estimatedReadingTime}m
                  </div>
                  <div className="text-sm text-gray-600 font-medium">Read Time</div>
                </div>
              </div>
            </div>

            {/* Professional Summary */}
            <div className="bg-gradient-to-br from-blue-50 via-purple-50 to-indigo-50 rounded-2xl p-8 border border-blue-200/50 shadow-xl hover:shadow-2xl transition-all duration-300">
              <div className="flex items-center space-x-3 mb-6">
                <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center">
                  <Lightbulb className="w-5 h-5 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900">AI-Generated Professional Summary</h3>
              </div>
              <div className="bg-white/70 backdrop-blur-sm rounded-xl p-6 border border-white/50">
                <div className="relative">
                  <div className="absolute top-0 left-0 text-4xl text-blue-300 font-serif">"</div>
                  <div className="absolute bottom-0 right-0 text-4xl text-blue-300 font-serif">"</div>
                  <p className="text-gray-700 leading-relaxed italic text-lg px-6 py-2 font-medium">
                    {TextFormatter.formatProfessionalSummary(analysisResults.professionalSummary)}
                  </p>
                </div>
              </div>
            </div>

            {/* Tabs */}
            <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl overflow-hidden border border-white/20 hover:shadow-2xl transition-all duration-300">
              <div className="border-b border-gray-200/50 bg-gradient-to-r from-gray-50 via-blue-50 to-purple-50">
                <nav className="flex flex-wrap gap-2 p-4">
                  {tabs.map((tab) => {
                    const colorClasses = {
                      blue: activeTab === tab.id ? 'bg-blue-500 text-white shadow-lg' : 'bg-blue-50 text-blue-700 hover:bg-blue-100',
                      green: activeTab === tab.id ? 'bg-green-500 text-white shadow-lg' : 'bg-green-50 text-green-700 hover:bg-green-100',
                      orange: activeTab === tab.id ? 'bg-orange-500 text-white shadow-lg' : 'bg-orange-50 text-orange-700 hover:bg-orange-100',
                      purple: activeTab === tab.id ? 'bg-purple-500 text-white shadow-lg' : 'bg-purple-50 text-purple-700 hover:bg-purple-100',
                      indigo: activeTab === tab.id ? 'bg-indigo-500 text-white shadow-lg' : 'bg-indigo-50 text-indigo-700 hover:bg-indigo-100'
                    };
                    
                    return (
                      <button
                        key={tab.id}
                        onClick={() => setActiveTab(tab.id)}
                        className={`flex-1 min-w-0 px-4 py-3 rounded-xl font-medium text-sm transition-all duration-300 flex flex-col items-center space-y-1 transform hover:scale-105 ${colorClasses[tab.color]}`}
                      >
                        <div className="flex items-center space-x-2">
                          <tab.icon className="w-4 h-4" />
                          <span className="font-semibold">{tab.label}</span>
                        </div>
                        {tab.description && (
                          <span className="text-xs opacity-80 hidden sm:block">
                            {tab.description}
                          </span>
                        )}
                      </button>
                    );
                  })}
                </nav>
              </div>

              <div className="p-8 bg-gradient-to-br from-white to-gray-50/50">
                {activeTab === 'summary' && (
                  <div className="prose max-w-none">
                    <div className="flex items-center space-x-3 mb-6">
                      <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center">
                        <FileText className="w-4 h-4 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900">Resume Summary</h3>
                    </div>
                    <FormattedContent content={analysisResults.summary} />
                  </div>
                )}

                {activeTab === 'strengths' && (
                  <div className="prose max-w-none">
                    <div className="flex items-center space-x-3 mb-6">
                      <div className="w-8 h-8 bg-gradient-to-br from-green-500 to-green-600 rounded-lg flex items-center justify-center">
                        <TrendingUp className="w-4 h-4 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900">Key Strengths</h3>
                    </div>
                    <FormattedContent content={analysisResults.strengths} />
                  </div>
                )}

                {activeTab === 'weaknesses' && (
                  <div className="prose max-w-none">
                    <div className="flex items-center space-x-3 mb-6">
                      <div className="w-8 h-8 bg-gradient-to-br from-orange-500 to-orange-600 rounded-lg flex items-center justify-center">
                        <AlertTriangle className="w-4 h-4 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900">Areas for Improvement</h3>
                    </div>
                    <FormattedContent content={analysisResults.weaknesses} />
                  </div>
                )}

                {activeTab === 'jobs' && (
                  <div className="prose max-w-none">
                    <div className="flex items-center space-x-3 mb-6">
                      <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-purple-600 rounded-lg flex items-center justify-center">
                        <Target className="w-4 h-4 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900">Recommended Job Titles</h3>
                    </div>
                    <FormattedContent content={analysisResults.jobTitles} />
                  </div>
                )}

                {activeTab === 'rating' && (
                  <div>
                    <div className="flex items-center space-x-3 mb-6">
                      <div className="w-8 h-8 bg-gradient-to-br from-indigo-500 to-indigo-600 rounded-lg flex items-center justify-center">
                        <BarChart3 className="w-4 h-4 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900">Professional Resume Rating</h3>
                    </div>
                    
                    {/* Overall Grade */}
                    <div className="mb-6 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border border-blue-200">
                      <div className="flex items-center justify-between">
                        <div>
                          <h4 className="text-lg font-bold text-blue-900">Overall Grade</h4>
                          <p className="text-blue-700">Based on professional recruiter standards</p>
                        </div>
                        <div className="text-right">
                          <div className="text-3xl font-bold text-blue-900">
                            {analysisResults.rating.totalScore}/10
                          </div>
                          <div className={`px-4 py-2 rounded-full text-sm font-semibold ${getGradeColor(analysisResults.rating.grade)}`}>
                            Grade: {analysisResults.rating.grade}
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Category Breakdown */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                      {[
                        { key: 'content', label: 'Content Quality', description: 'Clarity, relevance, and impact', icon: '📝' },
                        { key: 'structure', label: 'Structure & Flow', description: 'Organization and readability', icon: '🏗️' },
                        { key: 'formatting', label: 'Visual Formatting', description: 'Design and presentation', icon: '🎨' },
                        { key: 'impact', label: 'Achievement Impact', description: 'Quantified accomplishments', icon: '🎯' },
                        { key: 'ats', label: 'ATS Compatibility', description: 'Keyword optimization', icon: '🤖' }
                      ].map((item) => {
                        // Map rating properties to the correct keys
                        const scoreMap = {
                          content: analysisResults.rating.contentQuality || 0,
                          structure: analysisResults.rating.structureOrganization || 0,
                          formatting: analysisResults.rating.formattingDesign || 0,
                          impact: analysisResults.rating.impactLanguage || 0,
                          ats: analysisResults.rating.atsCompatibility || 0
                        };
                        const score = scoreMap[item.key] || 0;
                        const percentage = (score / 2) * 100;
                        return (
                          <div key={item.key} className="p-6 bg-gradient-to-br from-white to-gray-50 border border-gray-200/60 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105">
                            <div className="flex items-center justify-between mb-4">
                              <div className="flex items-center space-x-3">
                                <span className="text-2xl">{item.icon}</span>
                                <div>
                                  <span className="text-sm font-semibold text-gray-900">{item.label}</span>
                                  <p className="text-xs text-gray-600">{item.description}</p>
                                </div>
                              </div>
                              <span className={`px-3 py-1 rounded-full text-sm font-bold ${getScoreColor(score)}`}>
                                {score}/2
                              </span>
                            </div>
                            {/* Progress Bar */}
                            <div className="relative">
                              <div className="flex mb-2 items-center justify-between">
                                <div className="text-xs font-medium text-gray-700">Progress</div>
                                <div className="text-xs text-gray-600">{percentage.toFixed(0)}%</div>
                              </div>
                              <div className="overflow-hidden h-3 text-xs flex rounded-xl bg-gray-200">
                                <div 
                                  style={{ width: `${percentage}%` }}
                                  className={`shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center transition-all duration-1000 ease-out ${
                                    score >= 2 ? 'bg-gradient-to-r from-green-400 to-green-600' :
                                    score >= 1 ? 'bg-gradient-to-r from-yellow-400 to-yellow-600' :
                                    'bg-gradient-to-r from-red-400 to-red-600'
                                  }`}
                                ></div>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {/* Improvement Recommendations */}
                    {analysisResults.rating.improvements && analysisResults.rating.improvements.length > 0 && (
                      <div className="mt-6 p-4 bg-amber-50 rounded-lg border border-amber-200">
                        <h4 className="font-semibold text-amber-900 mb-3 flex items-center">
                          <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                          </svg>
                          Key Improvement Areas
                        </h4>
                        <ul className="text-amber-800 text-sm space-y-2">
                          {analysisResults.rating.improvements.map((improvement, index) => (
                            <li key={index} className="flex items-start">
                              <span className="inline-block w-2 h-2 bg-amber-400 rounded-full mt-1.5 mr-3 flex-shrink-0"></span>
                              <span>{improvement}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Rating Explanation */}
                    {analysisResults.rating.breakdown && (
                      <div className="mt-6 p-4 bg-gray-50 rounded-lg">
                        <h4 className="font-medium text-gray-900 mb-2">Detailed Analysis</h4>
                        <div className="text-gray-700 text-sm whitespace-pre-line">
                          {analysisResults.rating.breakdown}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Component for displaying formatted content with proper sections
const FormattedContent = ({ content }) => {
  if (!content) return null;

  const sections = TextFormatter.formatAsJSXSections(content);
  
  // If no sections were found, display as formatted text
  if (sections.length === 0) {
    return (
      <div className="text-gray-700 whitespace-pre-line leading-relaxed">
        {TextFormatter.formatAnalysisText(content)}
      </div>
    );
  }

  // Icon mapping for different section types
  const getSectionIcon = (header) => {
    const headerLower = header.toLowerCase();
    if (headerLower.includes('technical') || headerLower.includes('skills')) return '🔧';
    if (headerLower.includes('experience') || headerLower.includes('professional')) return '💼';
    if (headerLower.includes('education') || headerLower.includes('qualification')) return '🎓';
    if (headerLower.includes('leadership') || headerLower.includes('soft')) return '👥';
    if (headerLower.includes('achievement') || headerLower.includes('accomplishment')) return '🏆';
    if (headerLower.includes('background') || headerLower.includes('summary')) return '📋';
    if (headerLower.includes('missing') || headerLower.includes('gap')) return '⚠️';
    if (headerLower.includes('presentation') || headerLower.includes('formatting')) return '🎨';
    if (headerLower.includes('improvement') || headerLower.includes('suggestion')) return '💡';
    if (headerLower.includes('current') || headerLower.includes('level')) return '📍';
    if (headerLower.includes('growth') || headerLower.includes('advancement')) return '📈';
    if (headerLower.includes('different') || headerLower.includes('transfer')) return '🔄';
    if (headerLower.includes('emerging') || headerLower.includes('future')) return '🚀';
    return '📌'; // Default icon
  };

  const getGradientColor = (index) => {
    const gradients = [
      'from-blue-50 to-blue-100 border-blue-200',
      'from-purple-50 to-purple-100 border-purple-200',
      'from-green-50 to-green-100 border-green-200',
      'from-orange-50 to-orange-100 border-orange-200',
      'from-indigo-50 to-indigo-100 border-indigo-200',
      'from-pink-50 to-pink-100 border-pink-200',
    ];
    return gradients[index % gradients.length];
  };

  return (
    <div className="space-y-6">
      {sections.map((section, index) => (
        <div 
          key={index} 
          className={`bg-gradient-to-r ${getGradientColor(index)} rounded-2xl p-6 border-l-4 shadow-sm hover:shadow-md transition-all duration-300 transform hover:scale-[1.01]`}
        >
          {section.header && (
            <div className="flex items-center space-x-3 mb-4">
              <span className="text-2xl">{getSectionIcon(section.header)}</span>
              <h4 className="text-lg font-bold text-gray-900 leading-tight">
                {section.header}
              </h4>
            </div>
          )}
          <div className="text-gray-700 space-y-3">
            {section.content.map((paragraph, pIndex) => {
              const cleanParagraph = paragraph.trim();
              
              // Check if paragraph is a bullet point
              const bulletMatch = cleanParagraph.match(/^[-•*]|\d+\.\s/);
              const isBulletPoint = bulletMatch !== null;
              
              // Function to render text with bolding
              const renderWithBold = (text) => {
                // Split by the bold markdown, keeping the captured group
                const parts = text.split(/(\*\*.*?\*\*)/g).filter(part => part);
                return parts.map((part, i) =>
                  part.startsWith('**') && part.endsWith('**')
                    ? <strong key={i}>{part.slice(2, -2)}</strong>
                    : part
                );
              };

              if (isBulletPoint) {
                const bulletContent = cleanParagraph
                  .replace(/^[-•*]\s*/, '')
                  .replace(/^\d+\.\s*/, '');

                return (
                  <div key={pIndex} className="flex items-start space-x-3 bg-white/60 rounded-xl p-4 border border-white/50 hover:bg-white/80 transition-all duration-200 text-gray-800">
                    <span className="text-blue-500 mt-1 flex-shrink-0 text-lg font-bold">•</span>
                    <p className="leading-relaxed text-base flex-1">
                      {renderWithBold(bulletContent)}
                    </p>
                  </div>
                );
              }
              
              // Regular paragraph with enhanced styling
              if (cleanParagraph.length === 0) return null;

              return (
                <div key={pIndex} className="bg-white/60 rounded-xl p-4 border border-white/50 hover:bg-white/80 transition-all duration-200 text-gray-800">
                  <p className="leading-relaxed text-base font-medium">
                    {renderWithBold(cleanParagraph)}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
};

export default ResumeAnalyzer;